baseURL = 'https://potaxium.com/'
languageCode = 'en'
title = 'Potaxium'
googleAnalytics = 'G-LE24VW5RV7'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

# Lotus configuration
[params]
    google_fonts = [
        ["Roboto", "300, 400, 600, 700"],
        ["Arial", "300, 400, 600, 700"],
        ["Fira Code", "500, 700"]
    ]
    secondary_font = 'Roboto'
    mono_font = 'Fira Code'

[params.docs]
    darkMode = false
    sidebarIcons = true

[params.social]
    github = 'ZooidDino'

[params.footer]
    copyright = "© :YEAR: Zooid Dino"

[menus]
    [[menus.primary]]
        name  = "Documentation"
        url = "/docs/"
        identifier = "docs"
        weight = 1
    [[menus.primary]]
        name  = "Pricing"
        url = "/docs/pricing/"
        identifier = "pricing"
        weight = 2
    [[menus.primary]]
        name  = "Contact"
        url = "/docs/support"
        identifier = "contact"
        weight = 3
